
import java.awt.*;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class adminLogin extends javax.swing.JFrame {
    MobileCompany mobileCompany;
    Login login;

    /**
     * Creates new form adminUI
     */
    public adminLogin(MobileCompany c,Login login)  {
        this.login = login;
        mobileCompany = c;
        initComponents();
    }

    private adminLogin() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        comLab = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        companyArea = new javax.swing.JTextArea();
        reportButton1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        planText = new javax.swing.JTextField();
        findButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        planTextArea = new javax.swing.JTextArea();
        userCombo2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        ClearButtonPlan = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        pPlanRadioButton = new javax.swing.JRadioButton();
        bPlanRadioButton = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        planIdTF = new javax.swing.JTextField();
        userNameTF = new javax.swing.JTextField();
        modelTF = new javax.swing.JTextField();
        memorySizeTF = new javax.swing.JTextField();
        priceTF = new javax.swing.JTextField();
        internetQuotaTF = new javax.swing.JTextField();
        capLimitTF = new javax.swing.JTextField();
        dayTF = new javax.swing.JTextField();
        yearTF = new javax.swing.JTextField();
        abnOrCityTF = new javax.swing.JTextField();
        nOfEmploeesTF = new javax.swing.JTextField();
        osCombobox = new javax.swing.JComboBox<>();
        monthTF = new javax.swing.JTextField();
        clearAddPlanButton = new javax.swing.JButton();
        addAddPlanbutton = new javax.swing.JButton();
        userComboAddPlan = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        userCombo = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        userArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        userCombo1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        delBut = new javax.swing.JButton();
        updatebutton = new javax.swing.JButton();
        filterModelText = new javax.swing.JTextField();
        filterModelBut = new javax.swing.JButton();
        filterDateBut = new javax.swing.JButton();
        filterDateText = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        paymentTable = new javax.swing.JTable();
        sortPayment = new javax.swing.JCheckBox();
        sortUserName = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        repotTable = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        logOutMenu = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        comLab.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        comLab.setForeground(new java.awt.Color(0, 0, 0));

        companyArea.setBackground(new java.awt.Color(153, 255, 255));
        companyArea.setColumns(20);
        companyArea.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        companyArea.setRows(5);
        companyArea.setSelectedTextColor(new java.awt.Color(4, 62, 62));
        jScrollPane1.setViewportView(companyArea);

        reportButton1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        reportButton1.setText("Company Report");
        reportButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(381, 381, 381)
                        .addComponent(comLab, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(reportButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(678, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(reportButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(comLab, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(759, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Company Report", jPanel5);

        planText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planTextActionPerformed(evt);
            }
        });

        findButton.setText("Find Plan");
        findButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findButtonActionPerformed(evt);
            }
        });

        planTextArea.setBackground(new java.awt.Color(0, 255, 255));
        planTextArea.setColumns(20);
        planTextArea.setRows(5);
        jScrollPane2.setViewportView(planTextArea);

        userCombo2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                userCombo2ItemStateChanged(evt);
            }
        });
        userCombo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userCombo2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Users List");

        ClearButtonPlan.setForeground(new java.awt.Color(255, 0, 51));
        ClearButtonPlan.setText("Clear");
        ClearButtonPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonPlanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(userCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133)
                        .addComponent(planText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(findButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(ClearButtonPlan))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(802, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(planText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClearButtonPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(898, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Find Plan", jPanel7);

        buttonGroup2.add(pPlanRadioButton);
        pPlanRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pPlanRadioButton.setText("Personal Plan");
        pPlanRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                pPlanRadioButtonItemStateChanged(evt);
            }
        });
        pPlanRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pPlanRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(bPlanRadioButton);
        bPlanRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bPlanRadioButton.setSelected(true);
        bPlanRadioButton.setText("Bussiness Plan");
        bPlanRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                bPlanRadioButtonItemStateChanged(evt);
            }
        });
        bPlanRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPlanRadioButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Plan ID");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Username");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Mobile Phone");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Model");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("OS Type");
        jLabel8.setPreferredSize(new java.awt.Dimension(41, 22));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Memory Size");
        jLabel9.setPreferredSize(new java.awt.Dimension(108, 22));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Price");
        jLabel10.setPreferredSize(new java.awt.Dimension(36, 22));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Internet Quota");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Cap Limit");
        jLabel12.setPreferredSize(new java.awt.Dimension(41, 22));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Expiry Date");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Day");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Month");
        jLabel15.setPreferredSize(new java.awt.Dimension(48, 22));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Year");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("ABN");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("No. of Employees");

        planIdTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        planIdTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planIdTFActionPerformed(evt);
            }
        });

        userNameTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        userNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTFActionPerformed(evt);
            }
        });

        modelTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        memorySizeTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        memorySizeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memorySizeTFActionPerformed(evt);
            }
        });

        priceTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        internetQuotaTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        internetQuotaTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internetQuotaTFActionPerformed(evt);
            }
        });

        capLimitTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        capLimitTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capLimitTFActionPerformed(evt);
            }
        });

        dayTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        yearTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        abnOrCityTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        nOfEmploeesTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nOfEmploeesTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nOfEmploeesTFActionPerformed(evt);
            }
        });

        osCombobox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        this.osCombobox.setModel(new DefaultComboBoxModel(new String[]{"IOS", "ANDROID", "WINDOWS"}));
        osCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                osComboboxActionPerformed(evt);
            }
        });

        monthTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        clearAddPlanButton.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        clearAddPlanButton.setForeground(new java.awt.Color(255, 51, 51));
        clearAddPlanButton.setText("Clear");
        clearAddPlanButton.setToolTipText("");
        clearAddPlanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearAddPlanButtonActionPerformed(evt);
            }
        });

        addAddPlanbutton.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        addAddPlanbutton.setForeground(new java.awt.Color(255, 51, 51));
        addAddPlanbutton.setText("ADD");
        addAddPlanbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAddPlanbuttonActionPerformed(evt);
            }
        });

        userComboAddPlan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                userComboAddPlanItemStateChanged(evt);
            }
        });
        userComboAddPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userComboAddPlanActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel19.setText("Users List");

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel20.setText("Please select user that you want to add plan from users list:");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                                        .addGap(83, 83, 83)
                                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addGap(77, 77, 77)
                                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pPlanRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(9, 9, 9)))
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addGap(87, 87, 87)
                                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(userNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(planIdTF, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bPlanRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addGap(71, 71, 71)
                                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(osCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(modelTF, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(memorySizeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(priceTF, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(internetQuotaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(capLimitTF, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jLabel6))
                        .addGap(120, 120, 120)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dayTF, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(monthTF, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yearTF, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(abnOrCityTF, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nOfEmploeesTF, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clearAddPlanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addAddPlanbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel20)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(userComboAddPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(736, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userComboAddPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(48, 48, 48)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(clearAddPlanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(addAddPlanbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pPlanRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bPlanRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(modelTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(osCombobox))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(memorySizeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(priceTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(internetQuotaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(planIdTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(userNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dayTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(monthTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(yearTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(abnOrCityTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nOfEmploeesTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(capLimitTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(218, 218, 218))
        );

        jTabbedPane1.addTab("Add Plan", jPanel10);

        jPanel8.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPanel8PropertyChange(evt);
            }
        });

        userCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                userComboItemStateChanged(evt);
            }
        });
        userCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userComboActionPerformed(evt);
            }
        });

        userArea1.setBackground(new java.awt.Color(0, 255, 255));
        userArea1.setColumns(20);
        userArea1.setRows(5);
        jScrollPane3.setViewportView(userArea1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Users List");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(370, 370, 370)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(userCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(670, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(808, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("User Report", jPanel8);

        jPanel4.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPanel4PropertyChange(evt);
            }
        });

        userCombo1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                userCombo1ItemStateChanged(evt);
            }
        });
        userCombo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userCombo1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Users List");

        delBut.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        delBut.setForeground(new java.awt.Color(204, 0, 0));
        delBut.setText("Delete");
        delBut.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                delButItemStateChanged(evt);
            }
        });
        delBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delButActionPerformed(evt);
            }
        });

        updatebutton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        updatebutton.setForeground(new java.awt.Color(0, 0, 204));
        updatebutton.setText("Update");
        updatebutton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                updatebuttonItemStateChanged(evt);
            }
        });
        updatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebuttonActionPerformed(evt);
            }
        });

        filterModelText.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        filterModelText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterModelTextActionPerformed(evt);
            }
        });

        filterModelBut.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        filterModelBut.setForeground(new java.awt.Color(51, 0, 51));
        filterModelBut.setText("filter by Mobile Model");
        filterModelBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterModelButActionPerformed(evt);
            }
        });

        filterDateBut.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        filterDateBut.setForeground(new java.awt.Color(51, 0, 51));
        filterDateBut.setText("filter by expiry date");
        filterDateBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterDateButActionPerformed(evt);
            }
        });

        filterDateText.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updatebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delBut, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 427, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filterModelBut, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterDateBut, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filterDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterModelText, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(411, 411, 411))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delBut, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterDateBut, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterModelBut, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterModelText, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(846, Short.MAX_VALUE))
        );

        jTable2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Plan ID", "Username", "Model", "OS Type", "Memory Size ", "handset price", "Internet Quota", "Cap limit", "Expiry Date ", "City ", "ABN", "Number Of Emploee", "Monthly Payment"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(userCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(322, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Plans Information", jPanel4);

        paymentTable.setBackground(new java.awt.Color(204, 255, 204));
        paymentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(paymentTable);

        buttonGroup1.add(sortPayment);
        sortPayment.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sortPayment.setText("Sort By Montly Payment");
        sortPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortPaymentActionPerformed(evt);
            }
        });

        buttonGroup1.add(sortUserName);
        sortUserName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sortUserName.setSelected(true);
        sortUserName.setText("Sort by UserName");
        sortUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortUserNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(sortPayment)
                        .addGap(426, 426, 426)
                        .addComponent(sortUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(701, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sortPayment)
                    .addComponent(sortUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(799, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("User Total Payments", jPanel1);

        repotTable.setBackground(new java.awt.Color(204, 255, 204));
        repotTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        repotTable.setEnabled(false);
        jScrollPane6.setViewportView(repotTable);

        jTable1.setBackground(new java.awt.Color(204, 255, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setEnabled(false);
        jScrollPane7.setViewportView(jTable1);

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel21.setText("Report monthly payments by city");

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel22.setText("Report monthly payment and avergae payments by mobile model");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 1118, Short.MAX_VALUE)
                            .addComponent(jScrollPane7)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel22))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel21)))
                .addContainerGap(700, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Report Total Payments", jPanel3);

        logOutMenu.setText("Log Out");
        logOutMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(logOutMenu);
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1841, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 442, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 826, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        comLab.setText(mobileCompany.getName());
       ArrayList<String> nameAndId =new ArrayList<String>();
       for(User user :mobileCompany.getUsers().values() ){
       nameAndId.add(user.getName() + ":"+ user.getUserID());
       }
    this.userCombo.setModel(new DefaultComboBoxModel<>(nameAndId.toArray(new String [0])));
    this.userCombo1.setModel(new DefaultComboBoxModel<>(nameAndId.toArray(new String [0])));
    this.userCombo2.setModel(new DefaultComboBoxModel<>(nameAndId.toArray(new String [0])));
        this.userComboAddPlan.setModel(new DefaultComboBoxModel<>(nameAndId.toArray(new String [0])));

        fillTable1();
        fillTable2();
        fillTable3();
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void filterDateButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterDateButActionPerformed
        this.fillTable();
    }//GEN-LAST:event_filterDateButActionPerformed

    private void filterModelButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterModelButActionPerformed
        this.fillTable();
    }//GEN-LAST:event_filterModelButActionPerformed

    private void filterModelTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterModelTextActionPerformed

    }//GEN-LAST:event_filterModelTextActionPerformed

    private void updatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebuttonActionPerformed
        int ind = this.jTable2.getSelectedRow();
        String text = (String)userCombo1.getSelectedItem();
        String [] fields = text.split(":");
        int id = Integer.parseInt(fields[1]);
        User user=mobileCompany.getUsers().get(id);
        if (ind >= 0) {
            EditPlanAdmin updateUI = new EditPlanAdmin((MobilePlan) user.getPlans().get(Integer.parseInt((String) jTable2.getValueAt(ind, 0))), this);
            updateUI.setVisible(true);
        }
    }//GEN-LAST:event_updatebuttonActionPerformed

    private void updatebuttonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_updatebuttonItemStateChanged
        int ind = this.jTable2.getSelectedRow();
        String text = (String)userCombo1.getSelectedItem();
        String [] fields = text.split(":");
        int id = Integer.parseInt(fields[1]);
        User user=mobileCompany.getUsers().get(id);

    }//GEN-LAST:event_updatebuttonItemStateChanged

    private void delButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delButActionPerformed
        int ind = this.jTable2.getSelectedRow();
        String text = (String)userCombo1.getSelectedItem();
        String [] fields = text.split(":");
        int id = Integer.parseInt(fields[1]);
        User user=mobileCompany.getUsers().get(id);
        if (ind >= 0) {
            user.getPlans().remove(Integer.parseInt((String) jTable2.getValueAt(ind, 0)));
            this.fillTable();
        }
    }//GEN-LAST:event_delButActionPerformed

    private void delButItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_delButItemStateChanged

    }//GEN-LAST:event_delButItemStateChanged

    private void userCombo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userCombo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userCombo1ActionPerformed

    private void userCombo1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_userCombo1ItemStateChanged
        this.fillTable();

    }//GEN-LAST:event_userCombo1ItemStateChanged

    private void userComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userComboActionPerformed

    private void userComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_userComboItemStateChanged
        String text = (String)userCombo.getSelectedItem();
        String [] fields = text.split(":");
        int id = Integer.parseInt(fields[1]);
        userArea1.setText(mobileCompany.findUser(id,mobileCompany.getAdminUsername(),mobileCompany.getAdminPassword()).toString());
    }//GEN-LAST:event_userComboItemStateChanged

    private void findButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findButtonActionPerformed
       try{
        String id = (String) userCombo2.getSelectedItem();
       id = id.split(":")[1];
       User user = mobileCompany.findUser(Integer.parseInt(id),mobileCompany.getAdminUsername(),mobileCompany.getAdminPassword());
       MobilePlan mobilePlan = user.findPlan(Integer.parseInt(planText.getText()),user.getUserID(),user.getUserPassword());
        if(mobilePlan != null){
                   planTextArea.append(mobilePlan+"\n");
        }else{
                   JOptionPane.showMessageDialog(this,"Plan with id = " + planText.getText() + "  not found\n ");
        }
       }catch(NumberFormatException nfe){
       JOptionPane.showMessageDialog(this,"Please enter integer for Id ");}
       this.planText.setText("");
       
    }//GEN-LAST:event_findButtonActionPerformed

    private void planTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_planTextActionPerformed

    private void reportButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportButton1ActionPerformed
        companyArea.setText(mobileCompany.toString());
    }//GEN-LAST:event_reportButton1ActionPerformed

    private void sortPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortPaymentActionPerformed
        this.fillTable1();
    }//GEN-LAST:event_sortPaymentActionPerformed

    private void sortUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortUserNameActionPerformed
        this.fillTable1();
    }//GEN-LAST:event_sortUserNameActionPerformed

    private void jPanel4PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPanel4PropertyChange
        this.fillTable();
    }//GEN-LAST:event_jPanel4PropertyChange

    private void jPanel8PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPanel8PropertyChange
 String text = (String)userCombo.getSelectedItem();
        String [] fields = text.split(":");
        int id = Integer.parseInt(fields[1]);
        userArea1.setText(mobileCompany.findUser(id,mobileCompany.getAdminUsername(),mobileCompany.getAdminPassword()).toString());    }//GEN-LAST:event_jPanel8PropertyChange

    private void userCombo2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_userCombo2ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_userCombo2ItemStateChanged

    private void userCombo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userCombo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userCombo2ActionPerformed

    private void ClearButtonPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonPlanActionPerformed
        this.planTextArea.setText("");
    }//GEN-LAST:event_ClearButtonPlanActionPerformed

    private void pPlanRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pPlanRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pPlanRadioButtonActionPerformed

    private void bPlanRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPlanRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bPlanRadioButtonActionPerformed

    private void planIdTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planIdTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_planIdTFActionPerformed

    private void userNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTFActionPerformed

    private void capLimitTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capLimitTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_capLimitTFActionPerformed

    private void nOfEmploeesTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nOfEmploeesTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nOfEmploeesTFActionPerformed

    private void osComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_osComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_osComboboxActionPerformed

    private void clearAddPlanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearAddPlanButtonActionPerformed
        this.planIdTF.setText("");
        this.userNameTF.setText("");
        this.modelTF.setText("");
        this.memorySizeTF.setText("");
        this.priceTF.setText("");
        this.internetQuotaTF.setText("");
        this.capLimitTF.setText("");
        this.dayTF.setText("");
        this.monthTF.setText("");
        this.yearTF.setText("");
        this.abnOrCityTF.setText("");
        this.nOfEmploeesTF.setText("");    }//GEN-LAST:event_clearAddPlanButtonActionPerformed

    private void memorySizeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memorySizeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memorySizeTFActionPerformed

    private void userComboAddPlanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_userComboAddPlanItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_userComboAddPlanItemStateChanged

    private void userComboAddPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userComboAddPlanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userComboAddPlanActionPerformed

    private void addAddPlanbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAddPlanbuttonActionPerformed
        String ID = (String) userComboAddPlan.getSelectedItem();
        try {
            int id = Integer.parseInt(this.planIdTF.getText());
            String username = this.userNameTF.getText();
            String model = this.modelTF.getText();
            MobileType type = MobileType.valueOf(this.osCombobox.getSelectedItem().toString());
            int size = Integer.parseInt(this.memorySizeTF.getText());
            double price = Double.parseDouble(this.priceTF.getText());
            int quota = Integer.parseInt(this.internetQuotaTF.getText());
            int cap = Integer.parseInt(this.capLimitTF.getText());
            int day = Integer.parseInt(this.dayTF.getText());
            int month = Integer.parseInt(this.monthTF.getText());
            int year = Integer.parseInt(this.yearTF.getText());
            MyDate date = new MyDate(year, month, day);
            MobilePhone phone = new MobilePhone(model, type, size, price);
            MobilePlan plan = null;
            if (this.pPlanRadioButton.isSelected()) {
                String city = null;
                try {
                    city = this.abnOrCityTF.getText();
                    plan = new PersonalPlan(username, id, phone, quota, cap, city, date);
                } catch (PlanExceptionUserName peun) {
                    try {
                        username = peun.getNewUserName();
                        JOptionPane.showMessageDialog(this, peun);
                        plan = new PersonalPlan(username, id, phone, quota, cap, city, date);
                    }catch (PlanException pe){
                        id = pe.getNewID();
                        JOptionPane.showMessageDialog(this, pe);
                        plan = new PersonalPlan(username, id, phone, quota, cap, city, date);
                    }

                } catch (PlanException pe) {
                    id = pe.getNewID();
                    JOptionPane.showMessageDialog(this, pe);
                    plan = new PersonalPlan(username, id, phone, quota, cap, city, date);
                }
            } else {
                int noEmp = 0;
                int abn = 0;
                try {
                    abn = Integer.parseInt(this.abnOrCityTF.getText());
                    noEmp = Integer.parseInt(this.nOfEmploeesTF.getText());
                    plan = new BusinessPlan(username, id, phone, quota, cap, noEmp, abn, date);
                } catch (PlanExceptionUserName peun) {
                    try {
                        username = peun.getNewUserName();
                        JOptionPane.showMessageDialog(this, peun);
                        plan = new BusinessPlan(username, id, phone, quota, cap, noEmp, abn, date);
                    }catch (PlanException pe){
                        id = pe.getNewID();
                        JOptionPane.showMessageDialog(this, pe);
                        plan = new BusinessPlan(username, id, phone, quota, cap, noEmp, abn, date);
                    }
                } catch (PlanException pe) {
                    id = pe.getNewID();
                    JOptionPane.showMessageDialog(this, pe);
                    plan = new BusinessPlan(username, id, phone, quota, cap, noEmp, abn, date);
                }
            }

            if (mobileCompany.addPlan(Integer.parseInt(ID.split(":")[1]),plan,mobileCompany.getAdminUsername(),mobileCompany.getAdminPassword())) {
                JOptionPane.showMessageDialog(this, "Plan added successfully :)");
                this.planIdTF.setText("");
                this.userNameTF.setText("");
                this.modelTF.setText("");
                this.memorySizeTF.setText("");
                this.priceTF.setText("");
                this.internetQuotaTF.setText("");
                this.capLimitTF.setText("");
                this.dayTF.setText("");
                this.modelTF.setText("");
                this.yearTF.setText("");
                this.abnOrCityTF.setText("");
                this.nOfEmploeesTF.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Plan adding failed");
            }
        } catch (NumberFormatException | PlanException | PlanExceptionUserName e) {
            JOptionPane.showMessageDialog(this, e);
        }    }//GEN-LAST:event_addAddPlanbuttonActionPerformed

    private void internetQuotaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internetQuotaTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_internetQuotaTFActionPerformed

    private void bPlanRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_bPlanRadioButtonItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_bPlanRadioButtonItemStateChanged

    private void pPlanRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_pPlanRadioButtonItemStateChanged
        if(this.pPlanRadioButton.isSelected()){
            this.jLabel17.setText("City");
            this.jLabel18.setVisible(false);
            this.nOfEmploeesTF.setVisible(false);
        }else{
            this.jLabel17.setText("ABN");
            this.jLabel18.setVisible(true);
            this.nOfEmploeesTF.setVisible(true);
        }if(!this.pPlanRadioButton.isSelected() && this.bPlanRadioButton.isSelected()){
            this.bPlanRadioButton.setSelected(true);
        }     }//GEN-LAST:event_pPlanRadioButtonItemStateChanged

    private void logOutMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutMenuMouseClicked
this.dispose();
        this.login.setVisible(true);    }//GEN-LAST:event_logOutMenuMouseClicked
    
    public void fillTable() {
        String[] header = new String[]{"Plan ID", "username", "Model", "OS Type", "Memory Size", "handset price", "Internet Quota", "Cap Limit", "Expiry Date", "City", "ABN", "Number of Employees", "Monthly Payment"};
        DefaultTableModel model = new DefaultTableModel(header, 0);
        this.jTable2.setModel(model);
         String text = (String)userCombo1.getSelectedItem();
       String [] fields = text.split(":");
       int id = Integer.parseInt(fields[1]);
       User user=mobileCompany.getUsers().get(id);
       ArrayList<MobilePlan> plans=new ArrayList<>();
       for (MobilePlan plan : user.getPlans().values()) {
       plans.add(plan);
       }
       if(!this.filterModelText.getText().isEmpty()){
           plans=MobilePlan.filterByMobileModel(plans, this.filterModelText.getText());
       }
       
       if(!this.filterDateText.getText().isEmpty()){
            fields = this.filterDateText.getText().split("/");
                int year = Integer.parseInt(fields[0]);
                int month = Integer.parseInt(fields[1]);
                int day = Integer.parseInt(fields[2]);
                MyDate date = new MyDate(year, month, day);
                plans = MobilePlan.filterByExpiryDate(plans, date);
       }
       
        for (MobilePlan plan : plans) {
       
            String[] row = new String[13];
            row[0] = plan.getId() + "";
            row[1] = plan.userName;
            row[2] = plan.getHandsetModel();
            row[3] = plan.handset.getType().toString();
            row[4] = plan.handset.getMemorySize() + "";
            row[5] = plan.handset.getPrice() + "";
            row[6] = plan.internetQuota + "";
            row[7] = plan.capLimit + "";
            row[8] = plan.getExpiryDate().toString();
            if (plan instanceof PersonalPlan) {
                row[9] = ((PersonalPlan) plan).city;
                row[10] = "NA";
                row[11] = "NA";
            } else {
                row[9] = "NA";
                row[10] = ((BusinessPlan) plan).ABN + "";
                row[11] = ((BusinessPlan) plan).numberOfEmployees + "";
            }

            row[12] =  plan.calcPayment(10)+"";
            model.addRow(row);
        }
    }
          public void fillTable1() {
        String[] header = new String[]{"UserName", "MonthlyPayment"};
        DefaultTableModel model = new DefaultTableModel(header, 0);
        this.paymentTable.setModel(model);
        ArrayList<User> users=new ArrayList<>();
        for(User user: mobileCompany.getUsers().values()){
            users.add(user);
        }
       if(!this.sortUserName.isSelected())
           Collections.sort(users);
       if(this.sortPayment.isSelected())
           users.sort(Comparator.comparingDouble(x -> x.calcTotalPayments(mobileCompany.getFlatRate())));

           for (User user:users) {
            String[] row = new String[2];
            row[0] = user.getName();
            row[1] =  user.calcTotalPayments(10)+"";
            model.addRow(row);
        }
    }
             public void fillTable2() {
        String[] header = new String[]{"City Name", "Monthly Payment"};
        DefaultTableModel model = new DefaultTableModel(header, 0);
        this.repotTable.setModel(model);
        HashMap<String,Double> cityPayment = mobileCompany.getTotalPaymentPerCity();
        for(String city :cityPayment.keySet()){
            String[] row=new String[2];
            row[0]=city;
            row[1] = cityPayment.get(city) + "";
            model.addRow(row);
        }  
    }
     public void fillTable3() {
         String[] header = new String[]{"Mobile Model", "Monthly Payment","Average Payment"};
        DefaultTableModel model = new DefaultTableModel(header, 0);
        this.jTable1.setModel(model);
        HashMap<String, Double> hashMap1 = mobileCompany.getTotalPaymentPerMobileModel(10,mobileCompany.getAdminUsername(),mobileCompany.getAdminPassword());
        HashMap<String, Integer> hashMap2 = mobileCompany.getTotalCountPerMobileModel(mobileCompany.getAdminUsername(),mobileCompany.getAdminPassword());
        for (HashMap.Entry<String, Double> entry : hashMap1.entrySet()) {
            String[] row=new String[3];
            row[0]=entry.getKey();
            row[1]=entry.getValue()+"";
            row[2]= entry.getValue() / hashMap2.get(entry.getKey())+"";
            model.addRow(row);
        }
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearButtonPlan;
    private javax.swing.JTextField abnOrCityTF;
    private javax.swing.JButton addAddPlanbutton;
    private javax.swing.JRadioButton bPlanRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField capLimitTF;
    private javax.swing.JButton clearAddPlanButton;
    private javax.swing.JLabel comLab;
    private javax.swing.JTextArea companyArea;
    private javax.swing.JTextField dayTF;
    private javax.swing.JButton delBut;
    private javax.swing.JButton filterDateBut;
    private javax.swing.JTextField filterDateText;
    private javax.swing.JButton filterModelBut;
    private javax.swing.JTextField filterModelText;
    private javax.swing.JButton findButton;
    private javax.swing.JTextField internetQuotaTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JMenu logOutMenu;
    private javax.swing.JTextField memorySizeTF;
    private javax.swing.JTextField modelTF;
    private javax.swing.JTextField monthTF;
    private javax.swing.JTextField nOfEmploeesTF;
    private javax.swing.JComboBox<String> osCombobox;
    private javax.swing.JRadioButton pPlanRadioButton;
    private javax.swing.JTable paymentTable;
    private javax.swing.JTextField planIdTF;
    private javax.swing.JTextField planText;
    private javax.swing.JTextArea planTextArea;
    private javax.swing.JTextField priceTF;
    private javax.swing.JButton reportButton1;
    private javax.swing.JTable repotTable;
    private javax.swing.JCheckBox sortPayment;
    private javax.swing.JCheckBox sortUserName;
    private javax.swing.JButton updatebutton;
    private javax.swing.JTextArea userArea1;
    private javax.swing.JComboBox<String> userCombo;
    private javax.swing.JComboBox<String> userCombo1;
    private javax.swing.JComboBox<String> userCombo2;
    private javax.swing.JComboBox<String> userComboAddPlan;
    private javax.swing.JTextField userNameTF;
    private javax.swing.JTextField yearTF;
    // End of variables declaration//GEN-END:variables
}
