import java.io.Serializable;

public class PlanExceptionUserName extends Exception implements Serializable {
    private String userName;
    private String oldUserName;

    public PlanExceptionUserName(String userName) {
        this.oldUserName = userName;
        this.userName = generateID();
    }

    public String getNewUserName() {
        return userName;
    }

    public String generateID() {
        String userName = "USR";
        userName += (int)((Math.random() * ((999999 - 100000) + 1)) + 100000);
        userName+="U";
        return userName;
    }

    public String toString() {
        return "The Plan User Name " + oldUserName+ " was not valid and a new User Name (" + userName + ") is generated by admin and assigned for the Plan";
    }
}
