import java.io.Serializable;

public class PlanException extends Exception implements Serializable {

    private int id;
    private int oldId;

    public PlanException(int id) {
        this.oldId = id;
        this.id = generateID();
    }

    public int getNewID() {
        return id;
    }

    public int generateID() {
        return (int) ((Math.random() * ((3999999 - 3000000) + 1)) + 3000000);
    }

    public String toString() {
        return "The Plan ID " + oldId + " was not valid and a new ID (" + id + ") is generated by admin and assigned for the Plan";
    }
}
